hp:
  iter_per_epoch:
  - 20
  lr:
  # - 0.01
  - 0.1
  hidden_dim:
  - 64
  name:
  - gat
  - gcn
  - agnn
  - appnp
  only_gbdt:
  - true
  use_graphgbm:
  - 0.4
  - 0.2
  - 0
  dropout:
  - 0.
  # - 0.5
  depth:
  - 6
num_epochs: 40
patience: 10
